# Generated by Django 6.0 on 2025-12-22 23:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cleverminer_tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="celery_task_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
