# Generated by Django 6.0 on 2026-02-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cleverminer_tasks",
            "0005_dataset_file_format_dataset_is_ready_dataset_parent_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="run_snapshot",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
