# Generated by Django 6.0 on 2026-02-22 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cleverminer_tasks",
            "0007_dataset_dataset_clm_guidance_dataset_dataset_stats",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DatasetProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_stats", models.JSONField(blank=True, null=True)),
                ("dataset_clm_guidance", models.JSONField(blank=True, null=True)),
                ("dataset_columns", models.JSONField(blank=True, null=True)),
                ("schema_version", models.PositiveSmallIntegerField(default=1)),
                (
                    "dataset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="cleverminer_tasks.dataset",
                    ),
                ),
            ],
        ),
    ]
